type: object
properties:
  points:
    type: array
    items:
      type: object
      properties:
        currency:
          type: string
          example: USD
        value:
          type: number
          example: 27.55
