openapi: 3.0.3
info:
  version: 1.0.0
  title: Code Guard API
  description: >
    API documentation for the Code Guard project. Contains endpoints for authentication,
    sidebar data, transactions, etc.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: https://code-guard-backend.onrender.com
    description: Project's url

tags:
  - name: Auth
    description: Auth operations.
  - name: Transactions
    description: Transaction operations.
  - name: Users
    description: User operations.
  - name: Sidebar
    description: Data for displaying in the sidebar
  - name: Categories
    description: The list of available categories
  - name: Statistics
    description: Operations related to transaction statistics

paths:
  /auth/register:
    post:
      $ref: ../swagger/paths/auth/registration.yaml

  /auth/login:
    post:
      $ref: ../swagger/paths/auth/login.yaml

  /auth/logout:
    post:
      $ref: ../swagger/paths/auth/logout.yaml

  /users/currentUser:
    get:
      $ref: ../swagger/paths/users/currentUser.yaml

  /transactions:
    get:
      $ref: ../swagger/paths/transactions/get.yaml
    post:
      $ref: ../swagger/paths/transactions/post.yaml

  
  /transactions/{id}:
    patch:
      $ref: ../swagger/paths/transactions/{id}/patch.yaml
    delete:
      $ref: ../swagger/paths/transactions/{id}/delete.yaml
  
  /transactions/filter/by-date:
    get:
      $ref: ../swagger/paths/statistics/get.yaml

  /categories:
    get:
      $ref: ../swagger/paths/categories/get.yaml

  /sidebar/balance:
    get:
      $ref: ../swagger/paths/sidebar/balance.yaml

  /sidebar/exchange-rates:
    get:
      $ref: ../swagger/paths/sidebar/exchange-rates.yaml

  /sidebar/chart:
    get:
      $ref: ../swagger/paths/sidebar/chart.yaml

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer

  schemas:
    ExchangeRates:
      $ref: ../swagger/components/schemas/sidebar/ExchangeRates.yaml
    Chart:
      $ref: ../swagger/components/schemas/sidebar/Chart.yaml
