# openapi: 3.1.0
info:
  version: 1.0.0
  title: Money Guard
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: Expense tracking app
tags:
   - name: Money Guard
     description: Operations about transaction
  - name: Auth
    description: Auth operations.
# servers:
#   - url:
#   - url:
  paths:
    /auth/login:
     post:
       $ref: ../swagger/paths/auth/login.yaml

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
