openapi: 3.0.3
info:
  version: 1.0.0
  title: Code Guard API
  description: >
    API documentation for the Code Guard project. Contains endpoints for authentication,
    sidebar data, transactions, etc.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:3000
    description: Local development server

tags:
  - name: Auth
    description: Auth operations.
  - name: Transactions
    description: Transaction operations.
  - name: Sidebar
    description: Data for displaying in the sidebar

paths:
  /auth/logout:
    post:
      $ref: ../swagger/paths/auth/logout.yaml

  /transactions:
    get:
      $ref: ../swagger/paths/transactions/get.yaml

  /sidebar/exchange-rates:
    get:
      $ref: ../swagger/paths/sidebar/exchange-rates.yaml

  /sidebar/chart:
    get:
      $ref: ../swagger/paths/sidebar/chart.yaml

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    ExchangeRates:
      $ref: ../swagger/components/schemas/sidebar/ExchangeRates.yaml
    Chart:
      $ref: ../swagger/components/schemas/sidebar/Chart.yaml
