openapi: 3.0.3
info:
  version: 1.0.0
  title: Code Guard API
  description: |
    API documentation for the Code Guard project.
    Contains endpoints for authentication, sidebar data, transactions, etc.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:3000
    description: Local development server

tags:
  - name: Auth
    description: Auth operations.
  - name: Transactions
    description: Transaction operations.
  - name: Sidebar
    description: Data for displaying in the sidebar

paths:
  /transactions:
    get:
      $ref: ../swagger/paths/transactions/get.yaml

  /api/sidebar/balance:
    get:
      tags:
        - Sidebar
      summary: Get user balance
      responses:
        200:
          description: Balance retrieved
          content:
            application/json:
              schema:
                type: object
                properties:
                  balance:
                    type: number
                    example: 0.00

    patch:
      tags:
        - Sidebar
      summary: Update user balance
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - amount
              properties:
                amount:
                  type: number
                  example: 10000
      responses:
        200:
          description: Balance updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  balance:
                    type: number
                    example: 10000
        400:
          description: Invalid data (amount must be a number)
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: The "amount" field must be a number

  /api/sidebar/exchange-rates:
    get:
      tags:
        - Sidebar
      summary: Get exchange rates
      responses:
        200:
          description: Exchange rates
          content:
            application/json:
              schema:
                type: object
                example:
                  USD:
                    purchase: 27.55
                    sale: 27.65
                  EUR:
                    purchase: 30.00
                    sale: 30.10

  /api/sidebar/chart:
    get:
      tags:
        - Sidebar
      summary: Get chart data
      responses:
        200:
          description: Chart data
          content:
            application/json:
              schema:
                type: object
                properties:
                  points:
                    type: array
                    items:
                      type: object
                      properties:
                        currency:
                          type: string
                          example: USD
                        value:
                          type: number
                          example: 27.55

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
