# openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  # description:
tags:
  # - name:
  #   description:
  - name: Auth
    description: Auth operations.
  - name: Transactions
    description: Transaction operations.
servers:
  - url: http://localhost:3000
#   - url:
paths:
  /transactions:
    get:
      $ref: ../swagger/paths/transactions/get.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
