get:
  tags:
    - Sidebar
  summary: Get chart data (currency trend)
  description: Returns current currency exchange rates for chart visualization (e.g. USD, EUR to UAH).
  responses:
    '200':
      description: Successful response with chart data
      content:
        application/json:
          schema:
            $ref: '../../components/schemas/sidebar/Chart.yaml'
    '401':
      $ref: '../../components/responses/SidebarResponses/401.yaml'
    '500':
      $ref: '../../components/responses/SidebarResponses/500.yaml'
